name: Update README

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: 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
